### ISSUE TITLE
Unigram algorithm instead of BPE

### ISSUE THREAD

**Issue by nitinnairk** [lopuhin/transformer-lm#15]
Hi,
I was wondering if it would be possible to use the Unigram model that sentencepiece tokenizer defaults to rather than the BPE model which the GPT-2 model was built with? 
I do know XLNet does use this algorithm in its tokenizer.

**Comment by lopuhin** [comment]
Yes, both should work - one of them is a bit slower to train and uses more memory, but I don't recall which. I didn't notice big differences in tokenization quality between them.

**Comment by nitinnairk** [comment]
Thanks!
