### ISSUE TITLE
What's the 'max_sentence_length' when training sentencepiece model?

### ISSUE THREAD

**Issue by ty5491003** [lopuhin/transformer-lm#18]
I didn't find this parameter on [SentencePiece repo](https://github.com/google/sentencepiece), i want to know this parameter's effect and why default value is 16384.

**Comment by lopuhin** [comment]
Regarding this parameter, please see here https://github.com/google/sentencepiece/pull/239/files

The value 16384 was chosen empirically to capture most/all lines in a corpus I was working with, so you can adjust it accordingly. When sentencepiece is training, it will tell how many too long lines did it discard.

**Comment by ty5491003** [comment]
@lopuhin 
I get it, thanks for your timely reply. 😆
