### ISSUE TITLE
Training GPT-2 on very large corpus

### ISSUE THREAD

**Issue by simonefrancia** [lopuhin/transformer-lm#23]
Hi @lopuhin,
I'm using your repo in order to perform a training from scratch with custom very large corpora.
I have 3 files (train, valid and test ) that summed are 70 GB, train is 50 gb and now I am trying to encode that but it's a very long task and I don't know if this script handles eventual RAM problems.
Can I be quite? :) output is only one file??
Thanks

**Comment by lopuhin** [comment]
hi @simonefrancia re memory problems - the script tries to be smart, but it still needs to keep at least the results (probably more like 2x than that) in memory. How it tries to be smart: it does not keep text in memory, only encoded results - which is usually much smaller because it's 2 or 4 bytes per token, depending on the size of your vocabulary.

So I would suggest estimating memory usage and time on a sample.

**Comment by simonefrancia** [comment]
After 7 hours, the 59 GB file has finished :) now I wait for others.
Can it be also a problem for the train part?

**Comment by lopuhin** [comment]
Glad it finished :)

Training also keeps dataset in memory but should not use more memory then encoding - I think top usage should be less, approximately equal to the size of the output file.

**Comment by simonefrancia** [comment]
Hi,
i trained a model but when I try to generate text, an error occurred.
```Traceback (most recent call last):
  File "/usr/local/bin/gpt-2-gen", line 11, in <module>
    load_entry_point('lm==0.1.0', 'console_scripts', 'gpt-2-gen')()
  File "/usr/local/lib/python3.6/dist-packages/lm-0.1.0-py3.6.egg/lm/generate.py", line 21, in fire_gen_main
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 363, in _Fire
    filename, lineno = inspectutils.GetFileAndLine(component)
  File "/usr/local/lib/python3.6/dist-packages/fire/inspectutils.py", line 133, in GetFileAndLine
    unused_code, lineindex = inspect.findsource(component)
  File "/usr/lib/python3.6/inspect.py", line 828, in findsource
    if pat.match(lines[lnum]): break
IndexError: list index out of range
```
Do you know what can it be?
Thanks

**Comment by lopuhin** [comment]
Woah, from the traceback it looks like it's coming from https://github.com/google/python-fire/ library, but I didn't find anything in the issue tracker. I'm not 100% sure how to debug this, I see two options:

- maybe try uninstalling the package and installing it again,maybe making sure it's installed with ``python setup.py develop``?
- don't use fire, and call the generation function by other means

**Comment by simonefrancia** [comment]
Thank you very much, it works :) 
could you give me your mail , i would like to stay in touch with you.
It's a very cool project!
