### ISSUE TITLE
No speed up when using muli-gpu training 

### ISSUE THREAD

**Issue by zaidalyafeai** [lopuhin/transformer-lm#24]
Hey !

Thanks for amazing repository. I started working the single gpu training using the pytorch script. On P100 it estimates around 6 hours for one epoch. I was hoping that when running on 4x P100 that I would get 4x speed up. But it seems that I still get 6 hours per epoch. 

Zaid

**Comment by lopuhin** [comment]
yeah with 4 p100 I'd expect around 3x speedup. Could you please check if all gpus are being used with ``nvidia-smi``?

**Comment by zaidalyafeai** [comment]
![image](https://user-images.githubusercontent.com/15667714/75157888-14f20300-5726-11ea-883e-0d3dd56f9385.png)
They are all used

**Comment by zaidalyafeai** [comment]
@lopuhin I am getting a very strange behaviour. When I choose `n_devices = 2` explicitly I get a speed up ~ 2x with 9k it/s. For other values i.e 0, 1, 3, 4, I don't get any speed up (5k it/s).

**Comment by lopuhin** [comment]
I see, this is not expected and I don't even have good ideas here, sorry... I definitely run the code on 2 GPUs but not sure if I ever tried it on 4 (I think I did once but not sure).

I assume that main memory size is not an issue and it's not swapping?

> When I choose n_devices = 2 explicitly

You mean you change this line https://github.com/lopuhin/transformer-lm/blob/7f4141093d168b0fd15463045337d95facac9356/lm/main.py#L58 to an explicit value, right?

**Comment by zaidalyafeai** [comment]
Yeah I changed that line. I dont think memory is a problem but will double check.

**Comment by zaidalyafeai** [comment]
@lopuhin I tested it again but on 4xV100s and it seems to give 2.6 speed up. Not sure what was the problem. Closing for now.
