### ISSUE TITLE
Select GPU of choice

### ISSUE THREAD

**Issue by Meghana-Meghana** [lopuhin/transformer-lm#25]
Assuming there are 4 GPUs, how do I train on the GPU of choice instead of all the GPUs? I tried fiddling around with n_devices and device_id variables in main.py, but in vain.

**Comment by lopuhin** [comment]
@Meghana-Meghana you can set environment variable CUDA_VISIBLE_DEVICES, e.g. ``CUDA_VISIBLE_DEVICES=0 gpt-2 ...`` or to use two GPUs ``CUDA_VISIBLE_DEVICES=0,1 gpt-2 ...``
